ALTER TABLE orders
    ADD COLUMN product_id BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN quantity BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN delivery_time TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP;
