spring:
  application:
    name: order
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/order_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: 8003

delivery:
  min-delivery-time-minutes: ${DELIVERY_MIN_DELIVERY_TIME_MINUTES:30}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    distribution:
      sla:
        http.server.requests: 10ms, 50ms, 100ms, 200ms, 300ms, 400ms, 500ms, 600ms, 800ms
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.95,0.99

logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: DEBUG
    ru.otus.order: DEBUG
    org.springframework.security: DEBUG

services:
  billing:
    url: "http://billing-app:8001"
  notification:
    url: "http://notification-app:8002"
  delivery:
    url: "http://delivery:8005"
  stock:
    url: ${SERVICES_STOCK_URL:http://stock:8004}
  user:
    url: ${SERVICES_USER_URL:http://user-app:8000}